/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ensims.eplus.model;

import com.ensims.eplus.model.idf.IDF;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.PrintWriter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Yi
 */
public class JPanel_EPModelFilter extends javax.swing.JPanel {

    protected String MergeListFile = "mergeables.txt";
    protected JFileChooser fc = new JFileChooser("./");
    
    /**
     * Creates new form JPanel_EPModelFilter
     */
    public JPanel_EPModelFilter() {
        initComponents();
        try (BufferedReader fr = new BufferedReader (new FileReader(MergeListFile))) {
            String line = fr.readLine();
            while (line != null) {
                txaMergeable.append(line + "\n");
                line = fr.readLine();
            }
        }catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cmdSelect = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtOutputFile = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaMergeable = new javax.swing.JTextArea();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        cmdStart = new javax.swing.JButton();
        chkRemoveDup = new javax.swing.JCheckBox();
        txtInputFile = new javax.swing.JTextField();

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("This filter app is designed for reducing the size of E+ IDF files produced by some modelling tools. ");
        jLabel1.setOpaque(true);

        cmdSelect.setText("Select");
        cmdSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdSelectActionPerformed(evt);
            }
        });

        jLabel2.setText("The original IDF to be processed:");

        jLabel4.setText("File name for the filtered model:");

        txtOutputFile.setText("filtered.idf");

        jLabel5.setText("Object types to be filtered: ");

        txaMergeable.setColumns(20);
        txaMergeable.setRows(5);
        jScrollPane1.setViewportView(txaMergeable);

        cmdStart.setText("GO!");
        cmdStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdStartActionPerformed(evt);
            }
        });

        chkRemoveDup.setSelected(true);
        chkRemoveDup.setText("Remove duplicate objects");

        txtInputFile.setText("Select an IDF file...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 513, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtOutputFile)
                        .addGap(18, 18, 18)
                        .addComponent(chkRemoveDup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmdStart))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmdSelect)
                        .addGap(18, 18, 18)
                        .addComponent(txtInputFile)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmdSelect)
                    .addComponent(txtInputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtOutputFile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmdStart)
                    .addComponent(chkRemoveDup))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmdSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdSelectActionPerformed
        
        fc.setFileFilter(null);
        fc.setSelectedFile(new File(""));
        if (fc.showOpenDialog(this) == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            this.txtInputFile.setText(file.getAbsolutePath());
        } else {
            this.txtInputFile.setText("");
        }

    }//GEN-LAST:event_cmdSelectActionPerformed

    private void cmdStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdStartActionPerformed
        
        // Load IDF
        IDF idf = IDF.parseIDF(null, txtInputFile.getText().trim());
        // Save mergeable list to file
        try (PrintWriter fw = new PrintWriter (new FileWriter (MergeListFile))) {
            fw.println(txaMergeable.getText());
        }catch (Exception ex) {
            ex.printStackTrace();
        }
        // Do merge
        int n = EPModelFilter.mergeObjects (idf, MergeListFile, chkRemoveDup.isSelected());
        // Write output to file
        try (PrintWriter fw = new PrintWriter (new FileWriter (txtOutputFile.getText().trim()))) {
            fw.println(idf.exportModel());
        }catch (Exception ex) {
            ex.printStackTrace();
        }
        // Prompt result
        JOptionPane.showMessageDialog(this, "Model Filter: " + txtInputFile.getText().trim() + " >>> " + txtOutputFile.getText().trim() + ", " + n + " objects merged.");
        
    }//GEN-LAST:event_cmdStartActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox chkRemoveDup;
    private javax.swing.JButton cmdSelect;
    private javax.swing.JButton cmdStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea txaMergeable;
    private javax.swing.JTextField txtInputFile;
    private javax.swing.JTextField txtOutputFile;
    // End of variables declaration//GEN-END:variables
}
